import React, { useState } from 'react';
import '../App.css';

const ExplanationBox = ({ explanation }) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [showTechnical, setShowTechnical] = useState(false);
  
  const MAX_LENGTH = 250;
  const shouldTruncate = explanation && explanation.length > MAX_LENGTH;
  const displayText = shouldTruncate && !isExpanded && explanation
    ? explanation.substring(0, MAX_LENGTH) + '...' 
    : explanation;

  // Mock technical analysis for demo
  const technicalAnalysis = {
    indicators: [
      { name: 'Sensational Language', score: 65, status: 'high' },
      { name: 'Source Credibility', score: 42, status: 'medium' },
      { name: 'Factual Consistency', score: 78, status: 'low' },
      { name: 'Emotional Tone', score: 85, status: 'high' }
    ],
    algorithms: ['BERT', 'LSTM', 'Random Forest', 'XGBoost'],
    avgConfidence: 72
  };

  if (!explanation) return null;

  return (
    <div className="explanation-container">
      <div className="explanation-header">
        <h3>📊 Detailed Analysis</h3>
        <button 
          className="toggle-btn"
          onClick={() => setShowTechnical(!showTechnical)}
          type="button"
        >
          {showTechnical ? 'Hide Technical Details' : 'Show Technical Details'}
        </button>
      </div>
      
      <div className="explanation-content">
        <div className="explanation-text">
          <p>{displayText}</p>
          
          {shouldTruncate && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="read-more-btn"
              type="button"
            >
              {isExpanded ? '▲ Show Less' : '▼ Read More'}
            </button>
          )}
        </div>
        
        {showTechnical && (
          <div className="technical-analysis">
            <h4>Technical Analysis Breakdown</h4>
            
            <div className="indicators-grid">
              {technicalAnalysis.indicators.map((indicator, index) => (
                <div key={index} className="indicator-item">
                  <div className="indicator-header">
                    <span className="indicator-name">{indicator.name}</span>
                    <span className={`indicator-score ${indicator.status}`}>
                      {indicator.score}%
                    </span>
                  </div>
                  <div className="indicator-bar">
                    <div 
                      className="indicator-fill"
                      style={{ 
                        width: `${indicator.score}%`,
                        backgroundColor: indicator.status === 'high' ? '#e74c3c' : 
                                      indicator.status === 'medium' ? '#f39c12' : '#27ae60'
                      }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>
            
            <div className="algorithms-used">
              <h5>Algorithms Used:</h5>
              <div className="algorithm-tags">
                {technicalAnalysis.algorithms.map((algo, index) => (
                  <span key={index} className="algorithm-tag">
                    {algo}
                  </span>
                ))}
              </div>
            </div>
            
            <div className="confidence-score">
              <span>Overall Model Confidence:</span>
              <span className="confidence-value">
                {technicalAnalysis.avgConfidence}%
              </span>
            </div>
          </div>
        )}
      </div>
      
      <div className="disclaimer">
        <div className="disclaimer-icon">ℹ️</div>
        <div className="disclaimer-text">
          <strong>Disclaimer:</strong> This analysis is generated by AI models and should be used as a reference only. 
          Always verify information through multiple reliable sources before drawing conclusions.
        </div>
      </div>
    </div>
  );
};

export default ExplanationBox;